events {
    worker_connections 1024;
}

http {
    upstream fastapi {
        server capstone-fastapi:8000;
    }
    
    upstream nodejs {
        server capstone-nodejs:5000;
    }
    
    upstream springboot {
        server capstone-springboot:8081;
    }
    
    upstream dotnet {
        server capstone-dotnet:7000;
    }

    server {
        listen 80;
        
        location /api/fastapi/ {
            proxy_pass http://fastapi/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /api/nodejs/ {
            proxy_pass http://nodejs/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /api/springboot/ {
            proxy_pass http://springboot/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /api/dotnet/ {
            proxy_pass http://dotnet/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location / {
            return 404;
        }
    }
}
